### ISSUE TITLE
some checkpoint

### ISSUE THREAD

**Issue by ShaochengShen** [tqch/ddpm-torch#16]
HI!Your work is excellent. 
I would like to ask if you have pretrained models on the Celeb-HQ dataset or some else at different resolutions, such as 64x64, 128x128, and so on?

**Comment by tqch** [comment]
Hi! All the pretrained model weights are available in [*Releases*](https://github.com/tqch/ddpm-torch/releases) of this project: 

- CelebA-HQ 256x256 [download](https://github.com/tqch/ddpm-torch/releases/download/celeba_hq/celebahq_1200.pt)
- CelebA 64x64 [download](https://github.com/tqch/ddpm-torch/releases/download/checkpoints/celeba_600.pt)
- CIFAR-10 32x32 [download](https://github.com/tqch/ddpm-torch/releases/download/checkpoints/cifar10_2040.pt)

The purpose of this project is to reproduce the experimental results in the DDPM paper. Due to the computational resource and time limits, I only tried three datasets in certain resolutions, $i.e.$, CIFAR-10, CelebA, and CelebA-HQ.

**Comment by ShaochengShen** [comment]
Okay! Thank you for your response and sharing.
